### ISSUE TITLE
add-apt-repository not available after removing software-properties-common

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/repolib#44]
Based on the behavior observed while testing https://github.com/pop-os/repolib/pull/43, it would make sense to conflict with `software-properties-common` since we provide our own versions of the tools that `software-properties-common` would provide.

Sidestepping the package manager and installing a link from `/usr/lib/repolib/add-apt-repository` to `/usr/bin/add-apt-repository` in a postinst script creates corner cases such as the command not being available if `software-properties-common` was installed when `repolib` was installed but is later removed.

**Comment by isantop** [comment]
Conflicting with `software-properties-common` would mean breaking compatibility with a great many pieces of software in the Ubuntu repo without replacement functionality. We provide our own versions of the tools, but we do not replicate the library; the goal is in fact explicitly not to replicate that since it provides a great many things that simply aren't required in most cases. If we do set a `Conflicts:`, all Pop_OS installations become incompatible with `software-properties-common` and by extension all of that software. Resulting from this, many user installation of Pop could end up in a broken state when users remove repolib to gain access to that old software, and best case they are unable to use it. 

The actual functionality of repolib and its utilities does not conflict with `software-properties` and it doesn't make sense to exclude them arbitrarily. The correct solution is to use existing infrastructure (dpkg-triggers, Debian Alternatives) to provide our versions of conflicting utilities, and to leave the conflict resolution as-is.

**Comment by jacobgkau** [comment]
Just renaming the issue to be more in line with the symptom (which https://github.com/pop-os/repolib/pull/45 should fix) rather than the proposed solution that we're not going with right now.
